### ISSUE TITLE
Still Errors

### ISSUE THREAD

**Issue by redja150** [impsbro/Compiler440#1]
There are still errors in the code. They need fixed.
Although, I am more than happy to fix every bug and error in the system

**Comment by ChrisHersh** [comment]
Maybe the errors are supposed to be there, maybe, just maybe they're an artistic expression

**Comment by redja150** [comment]
Guys, the errors should be trending towards zero, not infinity. Its pretty simple, if your code introduces errors, dont push it. if it reduces errors, then by all means.

**Comment by ChrisHersh** [comment]
I think we should strive to approach a limit that is not 0 or infinity, like 42. 42 errors is a nice round number that we should strive for.

**Comment by redja150** [comment]
If thats the case, why not try for 42 warnings as well?

**Comment by ChrisHersh** [comment]
Well the issue there is that number depends on what warning settings you have, we could try for everyone to get a multiple of 42 warnings with some trickery

**Comment by ChrisHersh** [comment]
Like 420 warnings, that is a nice round number with no other meanings

**Comment by redja150** [comment]
That sounds about right

**Comment by ChrisHersh** [comment]
You okay there?

**Comment by redja150** [comment]
nope.

**Comment by ChrisHersh** [comment]
Good

**Comment by redja150** [comment]
Havent been for a while

**Comment by ChrisHersh** [comment]
I think that's required if Briggs is afraid of you

**Comment by redja150** [comment]
That, and all the errors start shorting some connections after a while

**Comment by IanKeefer** [comment]
This is not an AIM chat room.

**Comment by ChrisHersh** [comment]
@IAN, You're right.

**Comment by redja150** [comment]
@IanKeefer @ChrisHersh Actually, its a github chat room

**Comment by ChrisHersh** [comment]
Same thing really

**Comment by redja150** [comment]
Except this doesnt suck like AIM

**Comment by ChrisHersh** [comment]
We should make a better GitHub, but with AIM chat

**Comment by IanKeefer** [comment]
I don't have the bleep bloops when someone messages. Sadface

**Comment by ChrisHersh** [comment]
I do, it's coming from my pocket though

**Comment by IanKeefer** [comment]
@ChrisHersh @ChrisHersh @ChrisHersh @ChrisHersh @ChrisHersh @ChrisHersh

**Comment by redja150** [comment]
You might want to have that checked out....

**Comment by ChrisHersh** [comment]
WHAT DO YOU WANT FROM ME!?!?!?!?!?!?!?!!??!?!?!?!?!?!?!?!?!?!?!?!?!!??

**Comment by IanKeefer** [comment]
Fix the system m8

**Comment by ChrisHersh** [comment]
Yes

**Comment by IanKeefer** [comment]
We need more gotos and continues

**Comment by IanKeefer** [comment]
42 to be exact.

**Comment by ChrisHersh** [comment]
And breaks

**Comment by redja150** [comment]
I think a great multiple is needed, 42k maybe?

**Comment by shanjones** [comment]
please stop spaming me!!!

**Comment by IanKeefer** [comment]
TODO
- [ ] 42 Errors
- [ ] 42 Warnings
- [ ] 42 Gotos, continues, and breaks

**Comment by ChrisHersh** [comment]
I don't know, I think we should have fewer than 10K lines of code, so we need multiple ones per line

**Comment by redja150** [comment]
oooo. Fancy check boxes

**Comment by redja150** [comment]
42 per line?

**Comment by ChrisHersh** [comment]
@redja150 That works

**Comment by ChrisHersh** [comment]
+1

**Comment by ChrisHersh** [comment]
Also, @shanjones You can unsubscribe from this, or you can join in the madness

**Comment by IanKeefer** [comment]
ONE OF US. ONE OF US.

**Comment by ian** [comment]
+1

**Comment by cr7723** [comment]
lol wut

**Comment by ChrisHersh** [comment]
I....uh....huh. How did you find this? @Ian

**Comment by ChrisHersh** [comment]
Oh...wait I see, that is a really strange way of handling mentions. Not sure if I like it

**Comment by redja150** [comment]
@ChrisHersh you know you do.....

**Comment by IanKeefer** [comment]
Literally unplayable. 10/10 - IGN

**Comment by redja150** [comment]
@ZimmerMAX Yep

**Comment by ChrisHersh** [comment]
@thepure1 @thepure2 @thepure3 @thepure4 @thepure5 @thepure6  @thepure7 @thepure8 @thepure9 @thepure10 @thepure11 @thepure12  @thepure13 @thepure14 @thepure15 @thepure16 @thepure17 @thepure18  @thepure19 @thepure20

Just making sure I cover all of your accounts

**Comment by IanKeefer** [comment]
@mm7783

**Comment by redja150** [comment]
@ChrisHersh what if they go above 20?

**Comment by ChrisHersh** [comment]
That's a good point, but I'm too lazy to do it by hand, I'll need to write a script for that
